name: Trigger Backend Jenkins Pipeline

on:
  push:
    paths:
    - 'Application-Code/backend/**'

jobs:
  trigger-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Backend Jenkins Job
      run: |
        curl -X POST "https://34.235.152.62:8080/job/Three-tier-backend/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
